---
 
fp_dataset: metadata/samples-gmblind2.csv
fp_locus_attrs: metadata/locus_attrs.csv
fp_allele_names: metadata/known_alleles.csv
fp_genotypes_known: metadata/known_genotypes.csv
output:
  dp: results/gombe-blinded-test-2
  fp_rds: results.rds
report.hash_len: 6
report.group_samples: True
report.na.replicates: Pooled
report.title: Microsatellite Report - Gombe Second Blinded Panel
report.locus_chunks:
  "A-D": ["A", "B", "C", "D"]
  "1-4": ["1", "2", "3", "4"]
