---
 
fp_dataset: metadata/samples-round24.csv
fp_locus_attrs: metadata/locus_attrs.csv
fp_allele_names: metadata/known_alleles.csv
fp_genotypes_known: metadata/known_genotypes.csv
output:
  dp: results/gombe-round24
  fp_rds: results.rds
report.hash_len: 6
report.group_samples: False
report.title: Microsatellite Report - Gombe Comparison of MiSeq vs Sanger Methods
report.dist_max: 4
report.locus_chunks:
  "A-D": ["A", "B", "C", "D"]
  "1-4": ["1", "2", "3", "4"]
